obstacle_range:2.5
raytrace_range:10.0
footprint: [[0.30,0.25],[0.30,-0.25],[-0.50,-0.25],[-0.50,0.25]]
inflation_radius: 1.0
observation_sources: base_scan
base_scan: {
    sensor_frame: front_lrf_link,
    data_type: LaserScan,
    topic: front/scan,
    marking: true,
    clearing: true,
    max_obstacle_height: 1.0,
    min_obstacle_height: -0.15,
    expected_update_rate: 1.0,
    observation_persistence:0.0
}
